# Passive Network Asset Discovery Collector Config

mode=live
interface=wlp3s0
file=
url=http://localhost:8000/api/v1/ingest/asset-events
filter=arp or (udp and (port 67 or port 68)) or udp port 1900

# 0 means run continuously
count=0
batch_size=5
duration=0
